kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flask-pvc
  namespace: flask
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
