kind: PersistentVolume
apiVersion: v1
metadata:
  name: flask-pv
  labels:
    app: flask
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data
