apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: techwithsameer/flask-app-ecs
        ports:
        - containerPort: 80
